using System;
using System.Collections.Generic;

namespace Tripforo.Repository.EFCoreModels.ScaffoldedEntity
{
    public partial class FlightSearchResult
    {
        public int Id { get; set; }
        public string? Triptype { get; set; }
        public string? OrgDestFrom { get; set; }
        public string? OrgDestTo { get; set; }
        public string? DepartureLocation { get; set; }
        public string? DepartureCityName { get; set; }
        public string? DepAirportCode { get; set; }
        public string? DepartureAirportName { get; set; }
        public string? DepartureTerminal { get; set; }
        public string? ArrivalLocation { get; set; }
        public string? ArrivalCityName { get; set; }
        public string? ArrAirportCode { get; set; }
        public string? ArrivalAirportName { get; set; }
        public string? ArrivalTerminal { get; set; }
        public string? DepartureDate { get; set; }
        public string? DepartureTime { get; set; }
        public string? ArrivalDate { get; set; }
        public string? ArrivalTime { get; set; }
        public string? MarketingCarrier { get; set; }
        public string? OperatingCarrier { get; set; }
        public string? FlightIdentification { get; set; }
        public string? ValiDatingCarrier { get; set; }
        public string? AirLineName { get; set; }
        public string? ElectronicTicketing { get; set; }
        public string? ProductDetailQualifier { get; set; }
        public string? GetVia { get; set; }
        public string? BagInfo { get; set; }
        public string? ProviderUserId { get; set; }
        public string? AdtCabin { get; set; }
        public string? ChdCabin { get; set; }
        public string? InfCabin { get; set; }
        public string? AdtRbd { get; set; }
        public string? ChdRbd { get; set; }
        public string? InfRbd { get; set; }
        public string? AdtFareType { get; set; }
        public string? AdtFarebasis { get; set; }
        public string? ChdfareType { get; set; }
        public string? ChdFarebasis { get; set; }
        public string? InfFareType { get; set; }
        public string? InfFarebasis { get; set; }
        public string? InfFar { get; set; }
        public string? ChdFar { get; set; }
        public string? AdtFar { get; set; }
        public string? AdtBreakPoint { get; set; }
        public string? AdtAvlStatus { get; set; }
        public string? ChdBreakPoint { get; set; }
        public string? ChdAvlStatus { get; set; }
        public string? InfBreakPoint { get; set; }
        public string? InfAvlStatus { get; set; }
        public string? FareBasis { get; set; }
        public string? FbpaxType { get; set; }
        public string? Rbd { get; set; }
        public string? FareRule { get; set; }
        public string? FareDet { get; set; }
        public string? FlightNo { get; set; }
        public string? ClassType { get; set; }
        public double? Basicfare { get; set; }
        public double? Yq { get; set; }
        public double? Yr { get; set; }
        public double? Wo { get; set; }
        public double? Ot { get; set; }
        public double? GrossTotal { get; set; }
        public double? AdminMarkup { get; set; }
        public string? MarkupType { get; set; }
        public double? Markup { get; set; }
        public double? GrandTotal { get; set; }
        public DateTime? DepartureDate1 { get; set; }
        public DateTime? ArrivalDate1 { get; set; }
        public string? TotalSeats { get; set; }
        public string? UsedSeat { get; set; }
        public string? AvlSeat { get; set; }
        public DateTime? ValidTill { get; set; }
        public bool? Status { get; set; }
        public string? RtAirLineName { get; set; }
        public string? RtFlightNo { get; set; }
        public string? RtDepartureDate { get; set; }
        public string? RtDepartureTime { get; set; }
        public string? RtArrivalDate { get; set; }
        public string? RtArrivalTime { get; set; }
        public string? RtDepartureTerminal { get; set; }
        public string? RtArrivalTerminal { get; set; }
        public string? RtRbd { get; set; }
        public string? RtFareBasis { get; set; }
        public string? RtClassType { get; set; }
        public bool? FixedDepStatus { get; set; }
        public bool? Connect { get; set; }
        public int? SequenceNumber { get; set; }
        public string? RefNo { get; set; }
        public string? DepartureCityNameRef { get; set; }
        public string? DepAirportCodeRef { get; set; }
        public string? ArrivalCityNameRef { get; set; }
        public string? ArrAirportCodeRef { get; set; }
        public string? Duration { get; set; }
        public int? Leg { get; set; }
        public string? CreatedByUserid { get; set; }
        public double? InfFare { get; set; }
        public double? InfBfare { get; set; }
        public double? InfTax { get; set; }
        public double? InfMgtFee { get; set; }
        public string? SupMarkup { get; set; }
        public string? MarkupWithGst { get; set; }
        public bool? TempStatus { get; set; }
        public string? CreatedByName { get; set; }
        public bool? IsPrimary { get; set; }
    }
}
