using System;
using System.Collections.Generic;

namespace Tripforo.Repository.EFCoreModels.ScaffoldedEntity
{
    public partial class SelectedFlightDetailsGal
    {
        public string? OrgDestFrom { get; set; }
        public string? OrgDestTo { get; set; }
        public string? DepartureLocation { get; set; }
        public string? DepartureCityName { get; set; }
        public string? DepAirportCode { get; set; }
        public string? DepartureTerminal { get; set; }
        public string? ArrivalLocation { get; set; }
        public string? ArrivalCityName { get; set; }
        public string? ArrAirportCode { get; set; }
        public string? ArrivalTerminal { get; set; }
        public string? DepartureDate { get; set; }
        public string? DepartureDate1 { get; set; }
        public string? DepartureTime { get; set; }
        public string? ArrivalDate { get; set; }
        public string? ArrivalDate1 { get; set; }
        public string? ArrivalTime { get; set; }
        public int? Adult { get; set; }
        public int? Child { get; set; }
        public int? Infant { get; set; }
        public int? TotPax { get; set; }
        public string? MarketingCarrier { get; set; }
        public string? OperatingCarrier { get; set; }
        public string? FlightIdentification { get; set; }
        public string? ValiDatingCarrier { get; set; }
        public string? AirLineName { get; set; }
        public string? AvailableSeats { get; set; }
        public string? AdtCabin { get; set; }
        public string? ChdCabin { get; set; }
        public string? InfCabin { get; set; }
        public string? AdtRbd { get; set; }
        public string? ChdRbd { get; set; }
        public string? InfRbd { get; set; }
        public string? Rbd { get; set; }
        public string? AdtFare { get; set; }
        public string? AdtBfare { get; set; }
        public string? AdtTax { get; set; }
        public string? ChdFare { get; set; }
        public string? ChdBfare { get; set; }
        public string? ChdTax { get; set; }
        public string? InfFare { get; set; }
        public string? InfBfare { get; set; }
        public string? InfTax { get; set; }
        public string? TotalBfare { get; set; }
        public string? TotFare { get; set; }
        public string? TotalTax { get; set; }
        public decimal? NetFare { get; set; }
        public string? Stax { get; set; }
        public string? Tfee { get; set; }
        public string? DisCount { get; set; }
        public string? Searchvalue { get; set; }
        public string? LineItemNumber { get; set; }
        public string? Leg { get; set; }
        public string? Flight { get; set; }
        public string? Provider { get; set; }
        public string? TotDur { get; set; }
        public string? TripType { get; set; }
        public string? Eq { get; set; }
        public string? Stops { get; set; }
        public string? Trip { get; set; }
        public string? Sector { get; set; }
        public string? TripCnt { get; set; }
        public string? Currency { get; set; }
        public string? AdtadminMrk { get; set; }
        public string? AdtagentMrk { get; set; }
        public string? ChdadminMrk { get; set; }
        public string? ChdagentMrk { get; set; }
        public string? InfAdminMrk { get; set; }
        public string? InfAgentMrk { get; set; }
        public string? Iatacomm { get; set; }
        public string? AdtFareType { get; set; }
        public string? AdtFarebasis { get; set; }
        public string? ChdFareType { get; set; }
        public string? ChdFarebasis { get; set; }
        public string? InfFareType { get; set; }
        public string? InfFarebasis { get; set; }
        public string? FareBasis { get; set; }
        public string? FbpaxType { get; set; }
        public decimal? AdtFsur { get; set; }
        public decimal? ChdFsur { get; set; }
        public decimal? InfFsur { get; set; }
        public decimal? TotalFuelSur { get; set; }
        public string? Sno { get; set; }
        public string? Depdatelcc { get; set; }
        public string? Arrdatelcc { get; set; }
        public decimal? OriginalTf { get; set; }
        public decimal? OriginalTt { get; set; }
        public string? TrackId { get; set; }
        public string? FlightStatus { get; set; }
        public string? AdtTax1 { get; set; }
        public string? AdtOt { get; set; }
        public string? AdtSrvTax { get; set; }
        public string? ChdTax1 { get; set; }
        public string? ChdOt { get; set; }
        public string? ChdSrvTax { get; set; }
        public string? InfTax1 { get; set; }
        public string? InfOt { get; set; }
        public string? InfSrvTax { get; set; }
        public decimal? SrvTax { get; set; }
        public decimal? Tf { get; set; }
        public decimal? Tc { get; set; }
        public decimal? AdtTds { get; set; }
        public decimal? ChdTds { get; set; }
        public decimal? InfTds { get; set; }
        public decimal? AdtComm { get; set; }
        public decimal? ChdComm { get; set; }
        public decimal? InfComm { get; set; }
        public decimal? AdtCb { get; set; }
        public decimal? ChdCb { get; set; }
        public decimal? InfCb { get; set; }
        public string? ElectronicTicketing { get; set; }
        public string? UserId { get; set; }
        public int Counter { get; set; }
        public decimal? AdtMgtFee { get; set; }
        public decimal? ChdMgtFee { get; set; }
        public decimal? InfMgtFee { get; set; }
        public decimal? TotMgtFee { get; set; }
        public bool? IsCorp { get; set; }
        public DateTime? CreatedDate { get; set; }
        public decimal? AdtComm1 { get; set; }
        public decimal? ChdComm1 { get; set; }
        public string? AdtSrvTax1 { get; set; }
        public string? ChdSrvTax1 { get; set; }
        public bool? IsMobile { get; set; }
        public string? Resulttype { get; set; }
        public string? OldTrackId { get; set; }
        public string? AirlineRemark { get; set; }
        public string? SearchId { get; set; }
        public string? Pnrid { get; set; }
        public string? TicketId { get; set; }
        public bool? IsBagFare { get; set; }
        public string? Ssrcode { get; set; }
        public string? Adtstockistmrk { get; set; }
        public string? Chdstockistmrk { get; set; }
        public string? Inftockistmrk { get; set; }
        public decimal? Stadttds { get; set; }
        public decimal? Stchdtds { get; set; }
        public decimal? Stinftds { get; set; }
        public decimal? Stadtcomm { get; set; }
        public decimal? Stinfcomm { get; set; }
        public decimal? Stadtcb { get; set; }
        public decimal? Stchdcb { get; set; }
        public decimal? Stinfcb { get; set; }
        public decimal? Stadtcomm1 { get; set; }
        public decimal? Stchdcomm1 { get; set; }
        public string? Stiatacomm { get; set; }
        public string? FamilyFare { get; set; }
        public bool? IsSmefare { get; set; }
        public decimal? StchdComm { get; set; }
    }
}
